version: '3.8'

services:
  comfyui-logger:
    build: .
    container_name: comfyui-logger
    restart: unless-stopped
    volumes:
      # 挂载日志目录到宿主机
      - ./logs:/app/logs
      # 挂载时区文件
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    ports:
      # 可选：暴露端口用于健康检查
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
